FROM eclipse-temurin:21-jre-alpine
COPY target/customer*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]

# This line for test customer ci 999
# This line for test customer ci 4:37
# This line for test customer ci 4:38